name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -name: Get code
       uses: actions/checktou@v2
      -name: Install NodeJS
       uses: actions/setup-node@v3
       with:
          node-version: 18
      -name: Install dependencis
       run: npm ci
      -name: Run tests
       run: npm test
    